name: Nightly Tests

on:
  schedule:
    # Run at 2 AM UTC every day
    - cron: '0 2 * * *'
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  CI: true

jobs:
  full-test-suite:
    name: Full Test Suite on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          6.0.x
          7.0.x
          8.0.x
          9.0.x

    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/Directory.Build.props') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release
      env:
        CI: true

    - name: Run ALL tests (including slow)
      run: dotnet test --no-build --configuration Release --logger "trx;LogFileName=test-results-full.trx" --collect:"XPlat Code Coverage" --settings coverlet.runsettings
      timeout-minutes: 30
      env:
        CI: true

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-full-${{ matrix.os }}
        path: '**/test-results-full.trx'
        retention-days: 7

  performance-benchmark:
    name: Performance Benchmarks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x

    - name: Build Release
      run: dotnet build --configuration Release
      env:
        CI: true

    - name: Run performance tests
      run: |
        echo "=== Argon2 Performance ===" > performance.txt
        dotnet test --filter "FullyQualifiedName~Argon2&Category=Slow" --configuration Release --no-build --logger "console;verbosity=detailed" >> performance.txt
        echo "=== Blake2b Performance ===" >> performance.txt
        dotnet test --filter "FullyQualifiedName~Blake2b" --configuration Release --no-build --logger "console;verbosity=detailed" >> performance.txt
        echo "=== RSA/PGP Performance ===" >> performance.txt
        dotnet test --filter "FullyQualifiedName~Pgp&Category=Slow" --configuration Release --no-build --logger "console;verbosity=detailed" >> performance.txt

    - name: Upload performance results
      uses: actions/upload-artifact@v4
      with:
        name: performance-results
        path: performance.txt
        retention-days: 30
