blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: mailto:security@herocrypt.dev
    about: Please report security vulnerabilities via email, not as public issues
  - name: GitHub Discussions
    url: https://github.com/YourOrg/HeroCrypt/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/YourOrg/HeroCrypt/tree/main/docs
    about: Browse our documentation and guides
