name: 'Extract Build Configuration'
description: 'Extracts SDK versions and target frameworks from Directory.Build.props'
outputs:
  versions:
    description: 'The extracted SDK versions (newline-separated)'
    value: ${{ steps.extract.outputs.versions }}
  frameworks:
    description: 'The extracted target frameworks (JSON array)'
    value: ${{ steps.extract.outputs.frameworks }}
runs:
  using: 'composite'
  steps:
    - name: Extract supported SDK versions and frameworks from Directory.Build.props
      id: extract
      shell: bash
      run: |
        # Extract SupportedRuntimeSdkVersions from Directory.Build.props (portable approach)
        SDK_VERSIONS=$(sed -n 's/.*<SupportedRuntimeSdkVersions>\([^<]*\)<\/SupportedRuntimeSdkVersions>.*/\1/p' Directory.Build.props | tr ';' '\n')
        echo "versions<<EOF" >> $GITHUB_OUTPUT
        echo "$SDK_VERSIONS" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        echo "Extracted SDK versions:"
        echo "$SDK_VERSIONS"

        # Extract SupportedRuntimeTargetFrameworks from Directory.Build.props (portable approach)
        FRAMEWORKS=$(sed -n 's/.*<SupportedRuntimeTargetFrameworks>\([^<]*\)<\/SupportedRuntimeTargetFrameworks>.*/\1/p' Directory.Build.props)
        # Convert to JSON array format: ["net8.0", "net9.0", "net10.0"]
        # Using bash to convert without jq
        FRAMEWORKS_JSON="["
        FIRST=true
        IFS=';' read -ra FMKS <<< "$FRAMEWORKS"
        for fmk in "${FMKS[@]}"; do
          if [ "$FIRST" = true ]; then
            FRAMEWORKS_JSON="${FRAMEWORKS_JSON}\"${fmk}\""
            FIRST=false
          else
            FRAMEWORKS_JSON="${FRAMEWORKS_JSON},\"${fmk}\""
          fi
        done
        FRAMEWORKS_JSON="${FRAMEWORKS_JSON}]"
        echo "frameworks=$FRAMEWORKS_JSON" >> $GITHUB_OUTPUT
        echo "Extracted target frameworks: $FRAMEWORKS_JSON"
