using System.Security.Cryptography;
using HeroCrypt.Primitives.AesGcm;
using HeroCrypt.Tests.Infrastructure;

namespace HeroCrypt.Tests.Primitives.AesGcm;

/// <summary>
/// Comprehensive tests for AES-GCM (Galois/Counter Mode) implementation.
/// Follows HeroCrypt testing conventions - see TESTING_CONVENTIONS.md
/// </summary>
public class AesGcmCoreTests
{
    private const int KEY_SIZE_128 = 16;
    private const int KEY_SIZE_192 = 24;
    private const int KEY_SIZE_256 = 32;
    private const int NONCE_SIZE = 12;
    private const int TAG_SIZE = 16;

    /// <summary>
    /// Basic functionality tests for normal operations.
    /// </summary>
    [Trait("Category", TestCategories.UNIT)]
    [Trait("Category", TestCategories.FAST)]
    public class BasicFunctionality
    {
        [Fact]
        public void EncryptDecrypt_RoundTrip_Success()
        {
            // Arrange
            var key = TestHelpers.RandomBytes(KEY_SIZE_128);
            var nonce = TestHelpers.RandomBytes(NONCE_SIZE);
            var plaintext = TestHelpers.RandomBytes(TestDataSizes.Medium);

            // Act
            var result = AesGcmCore.Encrypt(plaintext, key, nonce);
            var decrypted = AesGcmCore.Decrypt(result.Ciphertext, key, result.Nonce);

            // Assert
            Assert.Equal(plaintext.Length + TAG_SIZE, result.Ciphertext.Length);
            CryptoAssertions.AssertBytesEqual(plaintext, decrypted);
        }

        [Fact]
        public void EncryptDecrypt_WithAssociatedData_Success()
        {
            // Arrange
            var key = TestHelpers.RandomBytes(KEY_SIZE_128);
            var nonce = TestHelpers.RandomBytes(NONCE_SIZE);
            var plaintext = TestHelpers.RandomBytes(TestDataSizes.Medium);
            var associatedData = TestHelpers.RandomBytes(TestDataSizes.Small);

            // Act
            var result = AesGcmCore.Encrypt(plaintext, key, nonce, associatedData);
            var decrypted = AesGcmCore.Decrypt(result.Ciphertext, key, result.Nonce, associatedData);

            // Assert
            Assert.Equal(plaintext.Length + TAG_SIZE, result.Ciphertext.Length);
            CryptoAssertions.AssertBytesEqual(plaintext, decrypted);
        }

        [Fact]
        public void EncryptDecrypt_WithoutAssociatedData_Success()
        {
            // Arrange
            var key = TestHelpers.RandomBytes(KEY_SIZE_128);
            var nonce = TestHelpers.RandomBytes(NONCE_SIZE);
            var plaintext = TestHelpers.RandomBytes(TestDataSizes.Medium);

            // Act
            var result = AesGcmCore.Encrypt(plaintext, key, nonce);
            var decrypted = AesGcmCore.Decrypt(result.Ciphertext, key, result.Nonce);

            // Assert
            CryptoAssertions.AssertBytesEqual(plaintext, decrypted);
        }

        [Fact]
        public void Encrypt_VariableKeySizes_Success()
        {
            var keySizes = new[] { KEY_SIZE_128, KEY_SIZE_192, KEY_SIZE_256 };
            foreach (var size in keySizes)
            {
                var key = TestHelpers.RandomBytes(size);
                var nonce = TestHelpers.RandomBytes(NONCE_SIZE);
                var plaintext = TestHelpers.RandomBytes(TestDataSizes.Small);

                var result = AesGcmCore.Encrypt(plaintext, key, nonce);
                var decrypted = AesGcmCore.Decrypt(result.Ciphertext, key, result.Nonce);

                CryptoAssertions.AssertBytesEqual(plaintext, decrypted);
            }
        }

        [Fact]
        public void Encrypt_WithAutoGeneratedNonce_Success()
        {
            // Arrange
            var key = TestHelpers.RandomBytes(KEY_SIZE_128);
            var plaintext = TestHelpers.RandomBytes(TestDataSizes.Medium);

            // Act - Don't provide nonce, let it auto-generate
            var result = AesGcmCore.Encrypt(plaintext, key);
            var decrypted = AesGcmCore.Decrypt(result.Ciphertext, key, result.Nonce);

            // Assert
            Assert.Equal(NONCE_SIZE, result.Nonce.Length);
            CryptoAssertions.AssertBytesEqual(plaintext, decrypted);
        }
    }

    /// <summary>
    /// Edge case tests for boundary conditions.
    /// </summary>
    [Trait("Category", TestCategories.EDGE_CASE)]
    [Trait("Category", TestCategories.FAST)]
    public class EdgeCases
    {
        [Fact]
        public void Encrypt_EmptyPlaintext_Success()
        {
            // Arrange
            var key = TestHelpers.RandomBytes(KEY_SIZE_128);
            var nonce = TestHelpers.RandomBytes(NONCE_SIZE);
            var plaintext = Array.Empty<byte>();

            // Act
            var result = AesGcmCore.Encrypt(plaintext, key, nonce);
            var decrypted = AesGcmCore.Decrypt(result.Ciphertext, key, result.Nonce);

            // Assert
            Assert.Equal(TAG_SIZE, result.Ciphertext.Length);
            Assert.Empty(decrypted);
        }

        [Fact]
        public void Encrypt_SingleByte_Success()
        {
            // Arrange
            var key = TestHelpers.RandomBytes(KEY_SIZE_128);
            var nonce = TestHelpers.RandomBytes(NONCE_SIZE);
            var plaintext = new byte[] { 0x42 };

            // Act
            var result = AesGcmCore.Encrypt(plaintext, key, nonce);
            var decrypted = AesGcmCore.Decrypt(result.Ciphertext, key, result.Nonce);

            // Assert
            Assert.Equal(1 + TAG_SIZE, result.Ciphertext.Length);
            CryptoAssertions.AssertBytesEqual(plaintext, decrypted);
        }

        [Fact]
        public void Encrypt_ExactBlockSize_Success()
        {
            // Arrange - 16 bytes (one AES block)
            var key = TestHelpers.RandomBytes(KEY_SIZE_128);
            var nonce = TestHelpers.RandomBytes(NONCE_SIZE);
            var plaintext = TestHelpers.RandomBytes(16);

            // Act
            var result = AesGcmCore.Encrypt(plaintext, key, nonce);
            var decrypted = AesGcmCore.Decrypt(result.Ciphertext, key, result.Nonce);

            // Assert
            CryptoAssertions.AssertBytesEqual(plaintext, decrypted);
        }

        [Fact]
        public void Encrypt_PartialBlock_Success()
        {
            // Arrange - 17 bytes (not multiple of block size)
            var key = TestHelpers.RandomBytes(KEY_SIZE_128);
            var nonce = TestHelpers.RandomBytes(NONCE_SIZE);
            var plaintext = TestHelpers.RandomBytes(17);

            // Act
            var result = AesGcmCore.Encrypt(plaintext, key, nonce);
            var decrypted = AesGcmCore.Decrypt(result.Ciphertext, key, result.Nonce);

            // Assert
            CryptoAssertions.AssertBytesEqual(plaintext, decrypted);
        }

        [Fact]
        [Trait("Category", TestCategories.SLOW)]
        public void Encrypt_LargeData_Success()
        {
            // Arrange - 1 MB
            var key = TestHelpers.RandomBytes(KEY_SIZE_256);
            var nonce = TestHelpers.RandomBytes(NONCE_SIZE);
            var plaintext = TestHelpers.RandomBytes(TestDataSizes.VeryLarge);

            // Act
            var result = AesGcmCore.Encrypt(plaintext, key, nonce);
            var decrypted = AesGcmCore.Decrypt(result.Ciphertext, key, result.Nonce);

            // Assert
            CryptoAssertions.AssertBytesEqual(plaintext, decrypted);
        }

        [Fact]
        public void Encrypt_EmptyAssociatedData_Success()
        {
            // Arrange
            var key = TestHelpers.RandomBytes(KEY_SIZE_128);
            var nonce = TestHelpers.RandomBytes(NONCE_SIZE);
            var plaintext = TestHelpers.RandomBytes(TestDataSizes.Small);
            var emptyAd = Array.Empty<byte>();

            // Act
            var result = AesGcmCore.Encrypt(plaintext, key, nonce, emptyAd);
            var decrypted = AesGcmCore.Decrypt(result.Ciphertext, key, result.Nonce, emptyAd);

            // Assert
            CryptoAssertions.AssertBytesEqual(plaintext, decrypted);
        }

        [Fact]
        public void Encrypt_LargeAssociatedData_Success()
        {
            // Arrange
            var key = TestHelpers.RandomBytes(KEY_SIZE_128);
            var nonce = TestHelpers.RandomBytes(NONCE_SIZE);
            var plaintext = TestHelpers.RandomBytes(TestDataSizes.Small);
            var largeAd = TestHelpers.RandomBytes(TestDataSizes.Large);

            // Act
            var result = AesGcmCore.Encrypt(plaintext, key, nonce, largeAd);
            var decrypted = AesGcmCore.Decrypt(result.Ciphertext, key, result.Nonce, largeAd);

            // Assert
            CryptoAssertions.AssertBytesEqual(plaintext, decrypted);
        }
    }

    /// <summary>
    /// Security-focused tests for cryptographic properties.
    /// </summary>
    [Trait("Category", TestCategories.SECURITY)]
    [Trait("Category", TestCategories.FAST)]
    public class Security
    {
        [Fact]
        public void Decrypt_ModifiedCiphertext_ThrowsCryptographicException()
        {
            // Arrange
            var key = TestHelpers.RandomBytes(KEY_SIZE_128);
            var nonce = TestHelpers.RandomBytes(NONCE_SIZE);
            var plaintext = TestHelpers.RandomBytes(TestDataSizes.Medium);

            var result = AesGcmCore.Encrypt(plaintext, key, nonce);

            // Act - Tamper with ciphertext
            var tamperedCiphertext = (byte[])result.Ciphertext.Clone();
            tamperedCiphertext[0] ^= 0xFF;

            // Assert
            Assert.Throws<CryptographicException>(() =>
                AesGcmCore.Decrypt(tamperedCiphertext, key, result.Nonce));
        }

        [Fact]
        public void Decrypt_ModifiedTag_ThrowsCryptographicException()
        {
            // Arrange
            var key = TestHelpers.RandomBytes(KEY_SIZE_128);
            var nonce = TestHelpers.RandomBytes(NONCE_SIZE);
            var plaintext = TestHelpers.RandomBytes(TestDataSizes.Medium);

            var result = AesGcmCore.Encrypt(plaintext, key, nonce);

            // Act - Tamper with tag (last 16 bytes)
            var tamperedCiphertext = (byte[])result.Ciphertext.Clone();
            tamperedCiphertext[^1] ^= 0xFF;

            // Assert
            Assert.Throws<CryptographicException>(() =>
                AesGcmCore.Decrypt(tamperedCiphertext, key, result.Nonce));
        }

        [Fact]
        public void Decrypt_ModifiedAssociatedData_ThrowsCryptographicException()
        {
            // Arrange
            var key = TestHelpers.RandomBytes(KEY_SIZE_128);
            var nonce = TestHelpers.RandomBytes(NONCE_SIZE);
            var plaintext = TestHelpers.RandomBytes(TestDataSizes.Medium);
            var associatedData = TestHelpers.RandomBytes(TestDataSizes.Small);

            var result = AesGcmCore.Encrypt(plaintext, key, nonce, associatedData);

            // Act - Tamper with AD
            var tamperedAD = TestHelpers.TamperFirst(associatedData);

            // Assert
            Assert.Throws<CryptographicException>(() =>
                AesGcmCore.Decrypt(result.Ciphertext, key, result.Nonce, tamperedAD));
        }

        [Fact]
        public void Decrypt_WrongKey_ThrowsCryptographicException()
        {
            // Arrange
            var key = TestHelpers.RandomBytes(KEY_SIZE_128);
            var wrongKey = TestHelpers.RandomBytes(KEY_SIZE_128);
            var nonce = TestHelpers.RandomBytes(NONCE_SIZE);
            var plaintext = TestHelpers.RandomBytes(TestDataSizes.Medium);

            var result = AesGcmCore.Encrypt(plaintext, key, nonce);

            // Assert
            Assert.Throws<CryptographicException>(() =>
                AesGcmCore.Decrypt(result.Ciphertext, wrongKey, result.Nonce));
        }

        [Fact]
        public void Decrypt_WrongNonce_ThrowsCryptographicException()
        {
            // Arrange
            var key = TestHelpers.RandomBytes(KEY_SIZE_128);
            var nonce = TestHelpers.RandomBytes(NONCE_SIZE);
            var wrongNonce = TestHelpers.RandomBytes(NONCE_SIZE);
            var plaintext = TestHelpers.RandomBytes(TestDataSizes.Medium);

            var result = AesGcmCore.Encrypt(plaintext, key, nonce);

            // Assert
            Assert.Throws<CryptographicException>(() =>
                AesGcmCore.Decrypt(result.Ciphertext, key, wrongNonce));
        }

        [Fact]
        public void Encrypt_SameInputDifferentNonce_ProducesDifferentCiphertext()
        {
            // Arrange
            var key = TestHelpers.RandomBytes(KEY_SIZE_128);
            var nonce1 = TestHelpers.RandomBytes(NONCE_SIZE);
            var nonce2 = TestHelpers.RandomBytes(NONCE_SIZE);
            var plaintext = TestHelpers.RandomBytes(TestDataSizes.Medium);

            // Act
            var result1 = AesGcmCore.Encrypt(plaintext, key, nonce1);
            var result2 = AesGcmCore.Encrypt(plaintext, key, nonce2);

            // Assert - Ciphertexts should be different
            Assert.NotEqual(result1.Ciphertext, result2.Ciphertext);
        }

        [Fact]
        public void Encrypt_OutputAppearsRandom()
        {
            // Arrange
            var key = TestHelpers.RandomBytes(KEY_SIZE_128);
            var nonce = TestHelpers.RandomBytes(NONCE_SIZE);
            var plaintext = TestHelpers.RandomBytes(TestDataSizes.Medium);

            // Act
            var result = AesGcmCore.Encrypt(plaintext, key, nonce);

            // Assert - Remove tag for randomness check
            var ciphertextOnly = result.Ciphertext.AsSpan(0, result.CiphertextLength).ToArray();
            CryptoAssertions.AssertAppearsRandom(ciphertextOnly);
        }
    }

    /// <summary>
    /// Parameter validation tests.
    /// </summary>
    [Trait("Category", TestCategories.UNIT)]
    [Trait("Category", TestCategories.FAST)]
    public class ParameterValidation
    {
        [Fact]
        public void Encrypt_InvalidKeySize_ThrowsArgumentException()
        {
            var invalidKey = new byte[15]; // Not 16, 24, 32
            var nonce = new byte[NONCE_SIZE];
            var plaintext = new byte[10];

            CryptoAssertions.AssertExceptionContains<ArgumentException>(
                () => AesGcmCore.Encrypt(plaintext, invalidKey, nonce),
                "16, 24, or 32 bytes");
        }

        [Fact]
        public void Encrypt_InvalidNonceSize_ThrowsArgumentException()
        {
            var key = new byte[KEY_SIZE_128];
            var invalidNonce = new byte[8]; // Not 12
            var plaintext = new byte[10];

            CryptoAssertions.AssertExceptionContains<ArgumentException>(
                () => AesGcmCore.Encrypt(plaintext, key, invalidNonce),
                "12 bytes");
        }

        [Fact]
        public void Decrypt_InvalidKeySize_ThrowsArgumentException()
        {
            var key = new byte[KEY_SIZE_128];
            var nonce = new byte[NONCE_SIZE];
            var plaintext = new byte[10];

            var result = AesGcmCore.Encrypt(plaintext, key, nonce);

            var invalidKey = new byte[15];
            CryptoAssertions.AssertExceptionContains<ArgumentException>(
                () => AesGcmCore.Decrypt(result.Ciphertext, invalidKey, nonce),
                "16, 24, or 32 bytes");
        }

        [Fact]
        public void Decrypt_InvalidNonceSize_ThrowsArgumentException()
        {
            var key = new byte[KEY_SIZE_128];
            var nonce = new byte[NONCE_SIZE];
            var plaintext = new byte[10];

            var result = AesGcmCore.Encrypt(plaintext, key, nonce);

            var invalidNonce = new byte[8];
            CryptoAssertions.AssertExceptionContains<ArgumentException>(
                () => AesGcmCore.Decrypt(result.Ciphertext, key, invalidNonce),
                "12 bytes");
        }

        [Fact]
        public void Decrypt_CiphertextTooShort_ThrowsArgumentException()
        {
            var key = new byte[KEY_SIZE_128];
            var nonce = new byte[NONCE_SIZE];
            var shortCiphertext = new byte[TAG_SIZE - 1]; // Less than tag size

            CryptoAssertions.AssertExceptionContains<ArgumentException>(
                () => AesGcmCore.Decrypt(shortCiphertext, key, nonce),
                $"at least {TAG_SIZE} bytes");
        }
    }

    /// <summary>
    /// Known Answer Tests for AES-GCM AEAD cipher.
    /// Tests verify determinism and correctness per NIST SP 800-38D.
    /// </summary>
    [Trait("Category", TestCategories.KNOWN_ANSWER)]
    [Trait("Category", TestCategories.COMPLIANCE)]
    [Trait("Category", TestCategories.FAST)]
    public class KnownAnswerTests
    {
        [Fact]
        public void AesGcm_EmptyMessage_ProducesTagOnly()
        {
            var key = TestHelpers.HexToBytes("000102030405060708090A0B0C0D0E0F");
            var nonce = TestHelpers.HexToBytes("CAFEBABEFACEDBADDECAF888");
            var plaintext = Array.Empty<byte>();
            var ad = Array.Empty<byte>();

            var result = AesGcmCore.Encrypt(plaintext, key, nonce, ad);

            // For empty plaintext, ciphertext is just the tag (16 bytes)
            Assert.Equal(TAG_SIZE, result.Ciphertext.Length);

            // Verify decryption
            var decrypted = AesGcmCore.Decrypt(result.Ciphertext, key, nonce, ad);
            Assert.Empty(decrypted);
        }

        [Fact]
        public void AesGcm_WithMessage_IsDeterministic()
        {
            var key = TestHelpers.HexToBytes("000102030405060708090A0B0C0D0E0F");
            var nonce = TestHelpers.HexToBytes("CAFEBABEFACEDBADDECAF888");
            var plaintext = TestHelpers.HexToBytes("00112233445566778899AABBCCDDEEFF");
            var ad = Array.Empty<byte>();

            var result1 = AesGcmCore.Encrypt(plaintext, key, nonce, ad);
            var result2 = AesGcmCore.Encrypt(plaintext, key, nonce, ad);

            CryptoAssertions.AssertBytesEqual(result1.Ciphertext, result2.Ciphertext);

            // Verify decryption
            var decrypted = AesGcmCore.Decrypt(result1.Ciphertext, key, nonce, ad);
            CryptoAssertions.AssertBytesEqual(plaintext, decrypted);
        }

        [Fact]
        public void AesGcm_EmptyPlaintextWithAD_ProducesTagOnly()
        {
            var key = TestHelpers.HexToBytes("000102030405060708090A0B0C0D0E0F");
            var nonce = TestHelpers.HexToBytes("CAFEBABEFACEDBADDECAF888");
            var plaintext = Array.Empty<byte>();
            var ad = TestHelpers.HexToBytes("FEEDFACEDEADBEEFFEEDFACEDEADBEEF");

            var result = AesGcmCore.Encrypt(plaintext, key, nonce, ad);

            Assert.Equal(TAG_SIZE, result.Ciphertext.Length);

            // Verify decryption
            var decrypted = AesGcmCore.Decrypt(result.Ciphertext, key, nonce, ad);
            Assert.Empty(decrypted);
        }

        [Fact]
        public void AesGcm_WithMessageAndAD_RoundTrip()
        {
            var key = TestHelpers.HexToBytes("000102030405060708090A0B0C0D0E0F");
            var nonce = TestHelpers.HexToBytes("CAFEBABEFACEDBADDECAF888");
            var plaintext = TestHelpers.HexToBytes("D9313225F88406E5A55909C5AFF5269A86A7A9531534F7DA2E4C303D8A318A72");
            var ad = TestHelpers.HexToBytes("FEEDFACEDEADBEEFFEEDFACEDEADBEEF");

            var result = AesGcmCore.Encrypt(plaintext, key, nonce, ad);

            // Ciphertext should be plaintext length + tag
            Assert.Equal(plaintext.Length + TAG_SIZE, result.Ciphertext.Length);

            // Verify decryption
            var decrypted = AesGcmCore.Decrypt(result.Ciphertext, key, nonce, ad);
            CryptoAssertions.AssertBytesEqual(plaintext, decrypted);
        }

        [Fact]
        public void AesGcm_Aes256_RoundTrip()
        {
            // Test with AES-256 (32-byte key)
            var key = TestHelpers.HexToBytes("000102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F");
            var nonce = TestHelpers.HexToBytes("CAFEBABEFACEDBADDECAF888");
            var plaintext = TestHelpers.HexToBytes("D9313225F88406E5A55909C5AFF5269A");
            var ad = TestHelpers.HexToBytes("FEEDFACEDEADBEEF");

            var result = AesGcmCore.Encrypt(plaintext, key, nonce, ad);
            var decrypted = AesGcmCore.Decrypt(result.Ciphertext, key, nonce, ad);

            CryptoAssertions.AssertBytesEqual(plaintext, decrypted);
        }

        [Fact]
        public void AesGcm_DifferentNonce_ProducesDifferentCiphertext()
        {
            var key = TestHelpers.HexToBytes("000102030405060708090A0B0C0D0E0F");
            var nonce1 = TestHelpers.HexToBytes("CAFEBABEFACEDBADDECAF888");
            var nonce2 = TestHelpers.HexToBytes("CAFEBABEFACEDBADDECAF889");
            var plaintext = TestHelpers.HexToBytes("00112233445566778899AABBCCDDEEFF");

            var result1 = AesGcmCore.Encrypt(plaintext, key, nonce1);
            var result2 = AesGcmCore.Encrypt(plaintext, key, nonce2);

            Assert.NotEqual(result1.Ciphertext, result2.Ciphertext);
        }

        [Fact]
        public void AesGcm_DifferentKey_ProducesDifferentCiphertext()
        {
            var key1 = TestHelpers.HexToBytes("000102030405060708090A0B0C0D0E0F");
            var key2 = TestHelpers.HexToBytes("0F0E0D0C0B0A09080706050403020100");
            var nonce = TestHelpers.HexToBytes("CAFEBABEFACEDBADDECAF888");
            var plaintext = TestHelpers.HexToBytes("00112233445566778899AABBCCDDEEFF");

            var result1 = AesGcmCore.Encrypt(plaintext, key1, nonce);
            var result2 = AesGcmCore.Encrypt(plaintext, key2, nonce);

            Assert.NotEqual(result1.Ciphertext, result2.Ciphertext);
        }
    }
}
