name: Security Scan

# CodeQL is handled by GitHub's default setup
# This workflow provides additional security checks beyond CodeQL

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * 1'  # Weekly on Monday
  workflow_dispatch:

permissions:
  contents: read
  actions: read

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  CI: true

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v5

    - name: Dependency Review
      uses: actions/dependency-review-action@v4
      with:
        fail-on-severity: moderate
        allow-licenses: MIT, Apache-2.0, BSD-2-Clause, BSD-3-Clause

  secrets-scan:
    name: Secrets Scanning
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Run TruffleHog
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: main
        head: HEAD
        extra_args: --debug --only-verified

  crypto-validation:
    name: Cryptographic Validation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v5

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x

    - name: Run RFC Compliance Tests
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet test --filter "Category=Compliance" --configuration Release --logger "console;verbosity=detailed"

    - name: Run Cryptographic Test Vectors
      run: |
        dotnet test --filter "Category=TestVectors" --configuration Release --logger "console;verbosity=detailed"

    - name: Validate Algorithm Implementations
      run: |
        dotnet test --filter "Category=AlgorithmValidation" --configuration Release --logger "console;verbosity=detailed"